security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|css|images|js)
            security: false

        # JWT nur für Login / Token
        api:
            pattern: ^/api/(login|token)
            stateless: true
            custom_authenticators:
                - App\Security\ApiJWTAuthenticator

        # Session / Cookie (Mood, Schüler, Lehrer)
        main:
            pattern: ^/
            lazy: true
            custom_authenticators:
                - App\Security\JWTAuthenticator

    access_control:
        - { path: ^/api/mood, roles: ROLE_SCHUELER }
        - { path: ^/api/lehrer, roles: ROLE_LEHRER }
        - { path: ^/api/schueler, roles: ROLE_SCHUELER }
